// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAiamXEeJ8fnhbpOAN7T2xpOhLCkNd6xQ',
    appId: '1:341486861196:web:77202fd1873b8e338734a9',
    messagingSenderId: '341486861196',
    projectId: 'flightsense-9ff33',
    authDomain: 'flightsense-9ff33.firebaseapp.com',
    storageBucket: 'flightsense-9ff33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh29_6jbhDN25x9XgG_WeGCJ-7V0Xb4GA',
    appId: '1:341486861196:android:6908c67b06c88d918734a9',
    messagingSenderId: '341486861196',
    projectId: 'flightsense-9ff33',
    storageBucket: 'flightsense-9ff33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAh8x2ZeT7VGYTt9IB5Esp5YpomnyA6mM',
    appId: '1:341486861196:ios:e984a64d5863dcc28734a9',
    messagingSenderId: '341486861196',
    projectId: 'flightsense-9ff33',
    storageBucket: 'flightsense-9ff33.appspot.com',
    iosBundleId: 'com.example.flightsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAh8x2ZeT7VGYTt9IB5Esp5YpomnyA6mM',
    appId: '1:341486861196:ios:0dec99fa5b0637e08734a9',
    messagingSenderId: '341486861196',
    projectId: 'flightsense-9ff33',
    storageBucket: 'flightsense-9ff33.appspot.com',
    iosBundleId: 'com.example.flightsense.RunnerTests',
  );
}
